openapi: 3.0.1
info:
  title: Proxy window for Star Wars
  version: v1
paths:
  /proxyapi/films:
    get:
      tags:
        - Flims
      summary: "Fetch all films"
      description: "To fetch all films details from Star Wars api"
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FilmViewModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FilmViewModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FilmViewModel'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
    post:
      tags:
        - Flims
      summary: "Fetch films by list of Id"
      description: "Post request to fetch multiple films deatils using id"
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: array of id
              items:
                type: integer
                format: int32
          text/json:
            schema:
              type: array
              items:
                type: integer
                format: int32
          application/*+json:
            schema:
              type: array
              items:
                type: integer
                format: int32
      responses:
        '200':
          description: Success
  /proxyapi/films/{id}:
    get:
      tags:
        - Flims
        
      summary: "Fetch a film by a single id"
      description: "To fetch particular film details using id"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/FilmViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/FilmViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/FilmViewModel'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
  /proxyapi/starships:
    get:
      tags:
        - StarShips
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StarShipViewModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StarShipViewModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StarShipViewModel'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
    post:
      tags:
        - StarShips
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int32
          text/json:
            schema:
              type: array
              items:
                type: integer
                format: int32
          application/*+json:
            schema:
              type: array
              items:
                type: integer
                format: int32
      responses:
        '200':
          description: Success
  /proxyapi/starships/{id}:
    get:
      tags:
        - StarShips
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StarShipViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/StarShipViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/StarShipViewModel'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
components:
  schemas:
    FilmViewModel:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        episode_id:
          type: integer
          format: int32
        opening_crawl:
          type: string
          nullable: true
        director:
          type: string
          nullable: true
        producer:
          type: string
          nullable: true
        rlease_date:
          type: string
          format: date-time
          nullable: true
        starships:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
      additionalProperties: false
    StarShipViewModel:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        model:
          type: string
          nullable: true
        manufacturer:
          type: string
          nullable: true
        consumables:
          type: string
          nullable: true
        films:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
      additionalProperties: false
